// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CommitTarget(arg1:string):Promise<model.DashboardState>;

export function GenerateCommitMessage():Promise<string>;

export function LoadState():Promise<model.DashboardState>;

export function PushTarget():Promise<model.DashboardState>;

export function Refresh():Promise<model.DashboardState>;

export function SaveConfig():Promise<model.DashboardState>;

export function SelectRepository(arg1:string):Promise<model.DashboardState>;

export function SelectRepositoryWorktree(arg1:string,arg2:string):Promise<model.DashboardState>;

export function SetAICommitAPIKey(arg1:string):Promise<model.DashboardState>;

export function SetDirection(arg1:string):Promise<model.DashboardState>;

export function SwapRepositories():Promise<model.DashboardState>;

export function SyncRepositories():Promise<model.DashboardState>;
