// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CommitTarget(arg1) {
  return window['go']['main']['App']['CommitTarget'](arg1);
}

export function GenerateCommitMessage() {
  return window['go']['main']['App']['GenerateCommitMessage']();
}

export function LoadState() {
  return window['go']['main']['App']['LoadState']();
}

export function PushTarget() {
  return window['go']['main']['App']['PushTarget']();
}

export function Refresh() {
  return window['go']['main']['App']['Refresh']();
}

export function SaveConfig() {
  return window['go']['main']['App']['SaveConfig']();
}

export function SelectRepository(arg1) {
  return window['go']['main']['App']['SelectRepository'](arg1);
}

export function SelectRepositoryWorktree(arg1, arg2) {
  return window['go']['main']['App']['SelectRepositoryWorktree'](arg1, arg2);
}

export function SetAICommitAPIKey(arg1) {
  return window['go']['main']['App']['SetAICommitAPIKey'](arg1);
}

export function SetDirection(arg1) {
  return window['go']['main']['App']['SetDirection'](arg1);
}

export function SwapRepositories() {
  return window['go']['main']['App']['SwapRepositories']();
}

export function SyncRepositories() {
  return window['go']['main']['App']['SyncRepositories']();
}
