// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {syncflow} from '../models';
import {settings} from '../models';
import {appsvc} from '../models';

export function AddFilesToProfile(arg1:string,arg2:Array<string>):Promise<void>;

export function ApplySnapshot(arg1:syncflow.ApplySnapshotRequest):Promise<syncflow.ApplySnapshotResult>;

export function ChooseFilesForProfile(arg1:string):Promise<Array<string>>;

export function ChooseSyncFile():Promise<string>;

export function CreateProfile(arg1:string):Promise<settings.Profile>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DownloadSync(arg1:boolean):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListSnapshots(arg1:string):Promise<Array<syncflow.SnapshotMeta>>;

export function LoadSettingsV2():Promise<settings.Data>;

export function PreviewApplyConflicts(arg1:syncflow.ApplySnapshotRequest):Promise<Array<syncflow.ApplyConflict>>;

export function PullProfilesFromCloud():Promise<number>;

export function QuickDownload(arg1:appsvc.QuickDownloadRequest):Promise<appsvc.QuickOperationResult>;

export function QuickUpload(arg1:appsvc.QuickUploadRequest):Promise<appsvc.QuickOperationResult>;

export function RemoveProfileItems(arg1:string,arg2:Array<string>):Promise<void>;

export function SaveSettingsV2(arg1:settings.Data):Promise<void>;

export function SetActiveProfile(arg1:string):Promise<void>;

export function SetProfileItemsEnabled(arg1:string,arg2:Array<string>,arg3:boolean):Promise<void>;

export function UploadProfile(arg1:string,arg2:Array<string>):Promise<syncflow.UploadProfileResult>;

export function UploadSync():Promise<string>;

export function ValidateMasterPassword(arg1:string,arg2:string):Promise<syncflow.MasterPasswordValidation>;
