// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFilesToProfile(arg1, arg2) {
  return window['go']['main']['App']['AddFilesToProfile'](arg1, arg2);
}

export function ApplySnapshot(arg1) {
  return window['go']['main']['App']['ApplySnapshot'](arg1);
}

export function ChooseFilesForProfile(arg1) {
  return window['go']['main']['App']['ChooseFilesForProfile'](arg1);
}

export function ChooseSyncFile() {
  return window['go']['main']['App']['ChooseSyncFile']();
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DownloadSync(arg1) {
  return window['go']['main']['App']['DownloadSync'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListSnapshots(arg1) {
  return window['go']['main']['App']['ListSnapshots'](arg1);
}

export function LoadSettingsV2() {
  return window['go']['main']['App']['LoadSettingsV2']();
}

export function PreviewApplyConflicts(arg1) {
  return window['go']['main']['App']['PreviewApplyConflicts'](arg1);
}

export function PullProfilesFromCloud() {
  return window['go']['main']['App']['PullProfilesFromCloud']();
}

export function QuickDownload(arg1) {
  return window['go']['main']['App']['QuickDownload'](arg1);
}

export function QuickUpload(arg1) {
  return window['go']['main']['App']['QuickUpload'](arg1);
}

export function RemoveProfileItems(arg1, arg2) {
  return window['go']['main']['App']['RemoveProfileItems'](arg1, arg2);
}

export function SaveSettingsV2(arg1) {
  return window['go']['main']['App']['SaveSettingsV2'](arg1);
}

export function SetActiveProfile(arg1) {
  return window['go']['main']['App']['SetActiveProfile'](arg1);
}

export function SetProfileItemsEnabled(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetProfileItemsEnabled'](arg1, arg2, arg3);
}

export function UploadProfile(arg1, arg2) {
  return window['go']['main']['App']['UploadProfile'](arg1, arg2);
}

export function UploadSync() {
  return window['go']['main']['App']['UploadSync']();
}

export function ValidateMasterPassword(arg1, arg2) {
  return window['go']['main']['App']['ValidateMasterPassword'](arg1, arg2);
}
