// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyFilterDraft() {
  return window['go']['main']['App']['ApplyFilterDraft']();
}

export function ApplyHistoryQuery(arg1) {
  return window['go']['main']['App']['ApplyHistoryQuery'](arg1);
}

export function ApplySavedFilter(arg1) {
  return window['go']['main']['App']['ApplySavedFilter'](arg1);
}

export function ClearVisible() {
  return window['go']['main']['App']['ClearVisible']();
}

export function CopyAllVisibleLogs() {
  return window['go']['main']['App']['CopyAllVisibleLogs']();
}

export function CopySelectedLogs() {
  return window['go']['main']['App']['CopySelectedLogs']();
}

export function CopyText(arg1) {
  return window['go']['main']['App']['CopyText'](arg1);
}

export function ExportVisibleLogs() {
  return window['go']['main']['App']['ExportVisibleLogs']();
}

export function GetSelectedLogRaw() {
  return window['go']['main']['App']['GetSelectedLogRaw']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function NextMatch() {
  return window['go']['main']['App']['NextMatch']();
}

export function Pause() {
  return window['go']['main']['App']['Pause']();
}

export function PrevMatch() {
  return window['go']['main']['App']['PrevMatch']();
}

export function ReplaceSavedFilterDefinitions(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReplaceSavedFilterDefinitions'](arg1, arg2, arg3);
}

export function ResumeDiscard() {
  return window['go']['main']['App']['ResumeDiscard']();
}

export function ResumeKeep() {
  return window['go']['main']['App']['ResumeKeep']();
}

export function SaveCurrentFilter(arg1) {
  return window['go']['main']['App']['SaveCurrentFilter'](arg1);
}

export function SaveFilterDefinition(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFilterDefinition'](arg1, arg2, arg3);
}

export function SelectDevice(arg1) {
  return window['go']['main']['App']['SelectDevice'](arg1);
}

export function SelectForegroundPackage() {
  return window['go']['main']['App']['SelectForegroundPackage']();
}

export function SelectLog(arg1) {
  return window['go']['main']['App']['SelectLog'](arg1);
}

export function SelectLogs(arg1) {
  return window['go']['main']['App']['SelectLogs'](arg1);
}

export function SelectPackage(arg1) {
  return window['go']['main']['App']['SelectPackage'](arg1);
}

export function SelectProcess(arg1) {
  return window['go']['main']['App']['SelectProcess'](arg1);
}

export function SetFilterDraft(arg1) {
  return window['go']['main']['App']['SetFilterDraft'](arg1);
}

export function SetPackageScope(arg1) {
  return window['go']['main']['App']['SetPackageScope'](arg1);
}

export function SetSearchQuery(arg1) {
  return window['go']['main']['App']['SetSearchQuery'](arg1);
}

export function UpdateSavedFilterDefinition(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSavedFilterDefinition'](arg1, arg2, arg3, arg4);
}
