// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {broadcast} from '../models';

export function DeleteTextHistory(arg1:string):Promise<void>;

export function ExportBroadcast(arg1:broadcast.ExportRequest):Promise<broadcast.ExportResult>;

export function GenerateBroadcast(arg1:broadcast.GenerateRequest):Promise<broadcast.GenerateResult>;

export function GetMinimaxSettings():Promise<broadcast.SettingsInfo>;

export function ListTextHistory():Promise<Array<broadcast.TextHistoryEntry>>;

export function SaveMinimaxSettings(arg1:broadcast.SettingsUpdate):Promise<broadcast.SettingsInfo>;
