// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {broadcast} from '../models';

export function ExportBroadcast(arg1:broadcast.ExportRequest):Promise<broadcast.ExportResult>;

export function GenerateBroadcast(arg1:broadcast.GenerateRequest):Promise<broadcast.GenerateResult>;
