// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveHistoryDeletePlan(arg1) {
  return window['go']['main']['App']['ApproveHistoryDeletePlan'](arg1);
}

export function BuildDeletePlan(arg1) {
  return window['go']['main']['App']['BuildDeletePlan'](arg1);
}

export function BuildHistoryDeletePlan(arg1) {
  return window['go']['main']['App']['BuildHistoryDeletePlan'](arg1);
}

export function ExecuteHistoryDeletePlan(arg1) {
  return window['go']['main']['App']['ExecuteHistoryDeletePlan'](arg1);
}

export function ExportHistoryEvidencePack(arg1) {
  return window['go']['main']['App']['ExportHistoryEvidencePack'](arg1);
}

export function GetCleanupWorkspaceConfig() {
  return window['go']['main']['App']['GetCleanupWorkspaceConfig']();
}

export function ListHistoryThreads(arg1) {
  return window['go']['main']['App']['ListHistoryThreads'](arg1);
}

export function RollbackHistoryDelete(arg1) {
  return window['go']['main']['App']['RollbackHistoryDelete'](arg1);
}

export function RunReadOnlyScan() {
  return window['go']['main']['App']['RunReadOnlyScan']();
}

export function SetCleanupWorkspaceRoot(arg1) {
  return window['go']['main']['App']['SetCleanupWorkspaceRoot'](arg1);
}
