// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {history} from '../models';
import {main} from '../models';

export function ApproveHistoryDeletePlan(arg1:history.ApproveRequest):Promise<history.ApproveResult>;

export function BuildDeletePlan(arg1:string):Promise<main.DeletePlanResult>;

export function BuildHistoryDeletePlan(arg1:history.BuildPlanRequest):Promise<history.PlanResult>;

export function ExecuteHistoryDeletePlan(arg1:history.ExecuteRequest):Promise<history.ExecuteResult>;

export function ExportHistoryEvidencePack(arg1:history.EvidencePackRequest):Promise<history.EvidencePackResult>;

export function GetCleanupWorkspaceConfig():Promise<main.CleanupWorkspaceConfig>;

export function ListHistoryThreads(arg1:history.ListRequest):Promise<history.ListResult>;

export function RollbackHistoryDelete(arg1:history.RollbackRequest):Promise<history.RollbackResult>;

export function RunReadOnlyScan():Promise<main.ScanResult>;

export function SetCleanupWorkspaceRoot(arg1:string):Promise<main.CleanupWorkspaceConfig>;
